// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdr_q7TVpND9qfJtqKPOKkaRLrtoc4IDQ',
    appId: '1:738352330717:web:5880860eb293e3b86b2834',
    messagingSenderId: '738352330717',
    projectId: 'flutterauth-5dfa5',
    authDomain: 'flutterauth-5dfa5.firebaseapp.com',
    storageBucket: 'flutterauth-5dfa5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvbBgYzKY7Bqf59Xlgd7MbXx1yLGyILf8',
    appId: '1:738352330717:android:188cc83289c66f856b2834',
    messagingSenderId: '738352330717',
    projectId: 'flutterauth-5dfa5',
    storageBucket: 'flutterauth-5dfa5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbeT4rT_bMTbNfL9Rcg3NLyzwfi_xq2PM',
    appId: '1:738352330717:ios:0b9dbfdf06cfd4fd6b2834',
    messagingSenderId: '738352330717',
    projectId: 'flutterauth-5dfa5',
    storageBucket: 'flutterauth-5dfa5.appspot.com',
    iosClientId: '738352330717-8b1653047fd5cpippk3hg19brk1necgp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbeT4rT_bMTbNfL9Rcg3NLyzwfi_xq2PM',
    appId: '1:738352330717:ios:0b9dbfdf06cfd4fd6b2834',
    messagingSenderId: '738352330717',
    projectId: 'flutterauth-5dfa5',
    storageBucket: 'flutterauth-5dfa5.appspot.com',
    iosClientId: '738352330717-8b1653047fd5cpippk3hg19brk1necgp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );
}
